# Generated by Django 2.2.2 on 2021-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cv', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techstack', models.CharField(max_length=200)),
                ('prospect', models.ManyToManyField(to='blottiobackend.Prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('prospect', models.ManyToManyField(to='blottiobackend.Prospect')),
            ],
        ),
    ]
