# Generated by Django 2.2.2 on 2021-02-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blottiobackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='prospect',
        ),
        migrations.AddField(
            model_name='prospect',
            name='techstack',
            field=models.ManyToManyField(to='blottiobackend.TechStack'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AddField(
            model_name='prospect',
            name='skills',
            field=models.ManyToManyField(to='blottiobackend.Skill'),
        ),
    ]
